###############################################################################
# @generated
# DO NOT MODIFY: This file is auto-generated by a crate_universe tool. To
# regenerate this file, run the following:
#
#     bazel run @//bazel/cargo:crates_vendor
###############################################################################
"""
# `crates_repository` API

- [aliases](#aliases)
- [crate_deps](#crate_deps)
- [all_crate_deps](#all_crate_deps)
- [crate_repositories](#crate_repositories)

"""

load("@bazel_skylib//lib:selects.bzl", "selects")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")

###############################################################################
# MACROS API
###############################################################################

# An identifier that represent common dependencies (unconditional).
_COMMON_CONDITION = ""

def _flatten_dependency_maps(all_dependency_maps):
    """Flatten a list of dependency maps into one dictionary.

    Dependency maps have the following structure:

    ```python
    DEPENDENCIES_MAP = {
        # The first key in the map is a Bazel package
        # name of the workspace this file is defined in.
        "workspace_member_package": {

            # Not all dependencies are supported for all platforms.
            # the condition key is the condition required to be true
            # on the host platform.
            "condition": {

                # An alias to a crate target.     # The label of the crate target the
                # Aliases are only crate names.   # package name refers to.
                "package_name":                   "@full//:label",
            }
        }
    }
    ```

    Args:
        all_dependency_maps (list): A list of dicts as described above

    Returns:
        dict: A dictionary as described above
    """
    dependencies = {}

    for workspace_deps_map in all_dependency_maps:
        for pkg_name, conditional_deps_map in workspace_deps_map.items():
            if pkg_name not in dependencies:
                non_frozen_map = dict()
                for key, values in conditional_deps_map.items():
                    non_frozen_map.update({key: dict(values.items())})
                dependencies.setdefault(pkg_name, non_frozen_map)
                continue

            for condition, deps_map in conditional_deps_map.items():
                # If the condition has not been recorded, do so and continue
                if condition not in dependencies[pkg_name]:
                    dependencies[pkg_name].setdefault(condition, dict(deps_map.items()))
                    continue

                # Alert on any miss-matched dependencies
                inconsistent_entries = []
                for crate_name, crate_label in deps_map.items():
                    existing = dependencies[pkg_name][condition].get(crate_name)
                    if existing and existing != crate_label:
                        inconsistent_entries.append((crate_name, existing, crate_label))
                    dependencies[pkg_name][condition].update({crate_name: crate_label})

    return dependencies

def crate_deps(deps, package_name = None):
    """Finds the fully qualified label of the requested crates for the package where this macro is called.

    Args:
        deps (list): The desired list of crate targets.
        package_name (str, optional): The package name of the set of dependencies to look up.
            Defaults to `native.package_name()`.

    Returns:
        list: A list of labels to generated rust targets (str)
    """

    if not deps:
        return []

    if package_name == None:
        package_name = native.package_name()

    # Join both sets of dependencies
    dependencies = _flatten_dependency_maps([
        _NORMAL_DEPENDENCIES,
        _NORMAL_DEV_DEPENDENCIES,
        _PROC_MACRO_DEPENDENCIES,
        _PROC_MACRO_DEV_DEPENDENCIES,
        _BUILD_DEPENDENCIES,
        _BUILD_PROC_MACRO_DEPENDENCIES,
    ]).pop(package_name, {})

    # Combine all conditional packages so we can easily index over a flat list
    # TODO: Perhaps this should actually return select statements and maintain
    # the conditionals of the dependencies
    flat_deps = {}
    for deps_set in dependencies.values():
        for crate_name, crate_label in deps_set.items():
            flat_deps.update({crate_name: crate_label})

    missing_crates = []
    crate_targets = []
    for crate_target in deps:
        if crate_target not in flat_deps:
            missing_crates.append(crate_target)
        else:
            crate_targets.append(flat_deps[crate_target])

    if missing_crates:
        fail("Could not find crates `{}` among dependencies of `{}`. Available dependencies were `{}`".format(
            missing_crates,
            package_name,
            dependencies,
        ))

    return crate_targets

def all_crate_deps(
        normal = False,
        normal_dev = False,
        proc_macro = False,
        proc_macro_dev = False,
        build = False,
        build_proc_macro = False,
        package_name = None):
    """Finds the fully qualified label of all requested direct crate dependencies \
    for the package where this macro is called.

    If no parameters are set, all normal dependencies are returned. Setting any one flag will
    otherwise impact the contents of the returned list.

    Args:
        normal (bool, optional): If True, normal dependencies are included in the
            output list.
        normal_dev (bool, optional): If True, normal dev dependencies will be
            included in the output list.
        proc_macro (bool, optional): If True, proc_macro dependencies are included
            in the output list.
        proc_macro_dev (bool, optional): If True, dev proc_macro dependencies are
            included in the output list.
        build (bool, optional): If True, build dependencies are included
            in the output list.
        build_proc_macro (bool, optional): If True, build proc_macro dependencies are
            included in the output list.
        package_name (str, optional): The package name of the set of dependencies to look up.
            Defaults to `native.package_name()` when unset.

    Returns:
        list: A list of labels to generated rust targets (str)
    """

    if package_name == None:
        package_name = native.package_name()

    # Determine the relevant maps to use
    all_dependency_maps = []
    if normal:
        all_dependency_maps.append(_NORMAL_DEPENDENCIES)
    if normal_dev:
        all_dependency_maps.append(_NORMAL_DEV_DEPENDENCIES)
    if proc_macro:
        all_dependency_maps.append(_PROC_MACRO_DEPENDENCIES)
    if proc_macro_dev:
        all_dependency_maps.append(_PROC_MACRO_DEV_DEPENDENCIES)
    if build:
        all_dependency_maps.append(_BUILD_DEPENDENCIES)
    if build_proc_macro:
        all_dependency_maps.append(_BUILD_PROC_MACRO_DEPENDENCIES)

    # Default to always using normal dependencies
    if not all_dependency_maps:
        all_dependency_maps.append(_NORMAL_DEPENDENCIES)

    dependencies = _flatten_dependency_maps(all_dependency_maps).pop(package_name, None)

    if not dependencies:
        if dependencies == None:
            fail("Tried to get all_crate_deps for package " + package_name + " but that package had no Cargo.toml file")
        else:
            return []

    crate_deps = list(dependencies.pop(_COMMON_CONDITION, {}).values())
    for condition, deps in dependencies.items():
        crate_deps += selects.with_or({
            tuple(_CONDITIONS[condition]): deps.values(),
            "//conditions:default": [],
        })

    return crate_deps

def aliases(
        normal = False,
        normal_dev = False,
        proc_macro = False,
        proc_macro_dev = False,
        build = False,
        build_proc_macro = False,
        package_name = None):
    """Produces a map of Crate alias names to their original label

    If no dependency kinds are specified, `normal` and `proc_macro` are used by default.
    Setting any one flag will otherwise determine the contents of the returned dict.

    Args:
        normal (bool, optional): If True, normal dependencies are included in the
            output list.
        normal_dev (bool, optional): If True, normal dev dependencies will be
            included in the output list..
        proc_macro (bool, optional): If True, proc_macro dependencies are included
            in the output list.
        proc_macro_dev (bool, optional): If True, dev proc_macro dependencies are
            included in the output list.
        build (bool, optional): If True, build dependencies are included
            in the output list.
        build_proc_macro (bool, optional): If True, build proc_macro dependencies are
            included in the output list.
        package_name (str, optional): The package name of the set of dependencies to look up.
            Defaults to `native.package_name()` when unset.

    Returns:
        dict: The aliases of all associated packages
    """
    if package_name == None:
        package_name = native.package_name()

    # Determine the relevant maps to use
    all_aliases_maps = []
    if normal:
        all_aliases_maps.append(_NORMAL_ALIASES)
    if normal_dev:
        all_aliases_maps.append(_NORMAL_DEV_ALIASES)
    if proc_macro:
        all_aliases_maps.append(_PROC_MACRO_ALIASES)
    if proc_macro_dev:
        all_aliases_maps.append(_PROC_MACRO_DEV_ALIASES)
    if build:
        all_aliases_maps.append(_BUILD_ALIASES)
    if build_proc_macro:
        all_aliases_maps.append(_BUILD_PROC_MACRO_ALIASES)

    # Default to always using normal aliases
    if not all_aliases_maps:
        all_aliases_maps.append(_NORMAL_ALIASES)
        all_aliases_maps.append(_PROC_MACRO_ALIASES)

    aliases = _flatten_dependency_maps(all_aliases_maps).pop(package_name, None)

    if not aliases:
        return dict()

    common_items = aliases.pop(_COMMON_CONDITION, {}).items()

    # If there are only common items in the dictionary, immediately return them
    if not len(aliases.keys()) == 1:
        return dict(common_items)

    # Build a single select statement where each conditional has accounted for the
    # common set of aliases.
    crate_aliases = {"//conditions:default": dict(common_items)}
    for condition, deps in aliases.items():
        condition_triples = _CONDITIONS[condition]
        for triple in condition_triples:
            if triple in crate_aliases:
                crate_aliases[triple].update(deps)
            else:
                crate_aliases.update({triple: dict(deps.items() + common_items)})

    return select(crate_aliases)

###############################################################################
# WORKSPACE MEMBER DEPS AND ALIASES
###############################################################################

_NORMAL_DEPENDENCIES = {
    "bazel/cargo": {
        _COMMON_CONDITION: {
            "ecdsa": Label("@cu//:ecdsa-0.16.0"),
            "getrandom": Label("@cu//:getrandom-0.2.14"),
            "hex": Label("@cu//:hex-0.4.3"),
            "hmac": Label("@cu//:hmac-0.12.1"),
            "log": Label("@cu//:log-0.4.20"),
            "lol_html": Label("@cu//:lol_html-2.0.0"),
            "once_cell": Label("@cu//:once_cell-1.19.0"),
            "p256": Label("@cu//:p256-0.13.0"),
            "proxy-wasm": Label("@cu//:proxy-wasm-0.2.1"),
            "rand_core": Label("@cu//:rand_core-0.6.4"),
            "regex": Label("@cu//:regex-1.9.6"),
            "serde": Label("@cu//:serde-1.0.197"),
            "serde_json": Label("@cu//:serde_json-1.0.114"),
            "sha2": Label("@cu//:sha2-0.10.8"),
            "url": Label("@cu//:url-2.4.0"),
            "uuid": Label("@cu//:uuid-1.24.0"),
            "zeroize": Label("@cu//:zeroize-1.8.1"),
        },
    },
}

_NORMAL_ALIASES = {
    "bazel/cargo": {
        _COMMON_CONDITION: {
        },
    },
}

_NORMAL_DEV_DEPENDENCIES = {
    "bazel/cargo": {
    },
}

_NORMAL_DEV_ALIASES = {
    "bazel/cargo": {
    },
}

_PROC_MACRO_DEPENDENCIES = {
    "bazel/cargo": {
    },
}

_PROC_MACRO_ALIASES = {
    "bazel/cargo": {
    },
}

_PROC_MACRO_DEV_DEPENDENCIES = {
    "bazel/cargo": {
    },
}

_PROC_MACRO_DEV_ALIASES = {
    "bazel/cargo": {
    },
}

_BUILD_DEPENDENCIES = {
    "bazel/cargo": {
    },
}

_BUILD_ALIASES = {
    "bazel/cargo": {
    },
}

_BUILD_PROC_MACRO_DEPENDENCIES = {
    "bazel/cargo": {
    },
}

_BUILD_PROC_MACRO_ALIASES = {
    "bazel/cargo": {
    },
}

_CONDITIONS = {
    "aarch64-linux-android": [],
    "cfg(all(any(target_os = \"linux\", target_os = \"android\"), not(any(all(target_os = \"linux\", target_env = \"\"), getrandom_backend = \"custom\", getrandom_backend = \"linux_raw\", getrandom_backend = \"rdrand\", getrandom_backend = \"rndr\"))))": ["@rules_rust//rust/platform:x86_64-unknown-linux-gnu"],
    "cfg(all(target_arch = \"aarch64\", target_os = \"linux\"))": [],
    "cfg(all(target_arch = \"aarch64\", target_vendor = \"apple\"))": [],
    "cfg(all(target_arch = \"loongarch64\", target_os = \"linux\"))": [],
    "cfg(all(target_os = \"uefi\", getrandom_backend = \"efi_rng\"))": [],
    "cfg(any())": [],
    "cfg(any(target_arch = \"aarch64\", target_arch = \"x86_64\", target_arch = \"x86\"))": ["@rules_rust//rust/platform:x86_64-unknown-linux-gnu"],
    "cfg(any(target_os = \"dragonfly\", target_os = \"freebsd\", target_os = \"hurd\", target_os = \"illumos\", target_os = \"cygwin\", all(target_os = \"horizon\", target_arch = \"arm\")))": [],
    "cfg(any(target_os = \"haiku\", target_os = \"redox\", target_os = \"nto\", target_os = \"aix\"))": [],
    "cfg(any(target_os = \"ios\", target_os = \"visionos\", target_os = \"watchos\", target_os = \"tvos\"))": [],
    "cfg(any(target_os = \"macos\", target_os = \"openbsd\", target_os = \"vita\", target_os = \"emscripten\"))": [],
    "cfg(not(all(target_arch = \"arm\", target_os = \"none\")))": ["@rules_rust//rust/platform:x86_64-unknown-linux-gnu"],
    "cfg(not(target_os = \"emscripten\"))": ["@rules_rust//rust/platform:x86_64-unknown-linux-gnu"],
    "cfg(target_os = \"emscripten\")": [],
    "cfg(target_os = \"netbsd\")": [],
    "cfg(target_os = \"solaris\")": [],
    "cfg(target_os = \"vxworks\")": [],
    "cfg(target_os = \"wasi\")": [],
    "cfg(unix)": ["@rules_rust//rust/platform:x86_64-unknown-linux-gnu"],
    "x86_64-unknown-linux-gnu": ["@rules_rust//rust/platform:x86_64-unknown-linux-gnu"],
}

###############################################################################

def crate_repositories():
    """A macro for defining repositories for all generated crates.

    Returns:
      A list of repos visible to the module through the module extension.
    """
    maybe(
        http_archive,
        name = "cu__ahash-0.8.12",
        sha256 = "5a15f179cd60c4584b8a8c596927aadc462e27f2ca70c04e0071964a73ba7a75",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/ahash/0.8.12/download"],
        strip_prefix = "ahash-0.8.12",
        build_file = Label("//bazel/cargo/remote:BUILD.ahash-0.8.12.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__aho-corasick-1.1.4",
        sha256 = "ddd31a130427c27518df266943a5308ed92d4b226cc639f5a8f1002816174301",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/aho-corasick/1.1.4/download"],
        strip_prefix = "aho-corasick-1.1.4",
        build_file = Label("//bazel/cargo/remote:BUILD.aho-corasick-1.1.4.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__base16ct-0.2.0",
        sha256 = "4c7f02d4ea65f2c1853089ffd8d2787bdbc63de2f0d29dedbcf8ccdfa0ccd4cf",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/base16ct/0.2.0/download"],
        strip_prefix = "base16ct-0.2.0",
        build_file = Label("//bazel/cargo/remote:BUILD.base16ct-0.2.0.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__bitflags-1.3.2",
        sha256 = "bef38d45163c2f1dde094a7dfd33ccf595c92905c8f8f4fdc18d06fb1037718a",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/bitflags/1.3.2/download"],
        strip_prefix = "bitflags-1.3.2",
        build_file = Label("//bazel/cargo/remote:BUILD.bitflags-1.3.2.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__bitflags-2.13.0",
        sha256 = "b4388bee8683e3d04af747c73422af53102d2bd24d9eadb6cbc100baef4b43f8",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/bitflags/2.13.0/download"],
        strip_prefix = "bitflags-2.13.0",
        build_file = Label("//bazel/cargo/remote:BUILD.bitflags-2.13.0.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__block-buffer-0.10.4",
        sha256 = "3078c7629b62d3f0439517fa394996acacc5cbc91c5a20d8c658e77abd503a71",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/block-buffer/0.10.4/download"],
        strip_prefix = "block-buffer-0.10.4",
        build_file = Label("//bazel/cargo/remote:BUILD.block-buffer-0.10.4.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__bumpalo-3.20.3",
        sha256 = "72f5acc6cb2ba439de613abc23857ec3d78374d8ed5ac84e9d11336e87da8649",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/bumpalo/3.20.3/download"],
        strip_prefix = "bumpalo-3.20.3",
        build_file = Label("//bazel/cargo/remote:BUILD.bumpalo-3.20.3.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__byteorder-1.5.0",
        sha256 = "1fd0f2584146f6f2ef48085050886acf353beff7305ebd1ae69500e27c67f64b",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/byteorder/1.5.0/download"],
        strip_prefix = "byteorder-1.5.0",
        build_file = Label("//bazel/cargo/remote:BUILD.byteorder-1.5.0.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__cfg-if-1.0.4",
        sha256 = "9330f8b2ff13f34540b44e946ef35111825727b38d33286ef986142615121801",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/cfg-if/1.0.4/download"],
        strip_prefix = "cfg-if-1.0.4",
        build_file = Label("//bazel/cargo/remote:BUILD.cfg-if-1.0.4.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__const-oid-0.9.6",
        sha256 = "c2459377285ad874054d797f3ccebf984978aa39129f6eafde5cdc8315b612f8",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/const-oid/0.9.6/download"],
        strip_prefix = "const-oid-0.9.6",
        build_file = Label("//bazel/cargo/remote:BUILD.const-oid-0.9.6.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__convert_case-0.4.0",
        sha256 = "6245d59a3e82a7fc217c5828a6692dbc6dfb63a0c8c90495621f7b9d79704a0e",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/convert_case/0.4.0/download"],
        strip_prefix = "convert_case-0.4.0",
        build_file = Label("//bazel/cargo/remote:BUILD.convert_case-0.4.0.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__cpufeatures-0.2.17",
        sha256 = "59ed5838eebb26a2bb2e58f6d5b5316989ae9d08bab10e0e6d103e656d1b0280",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/cpufeatures/0.2.17/download"],
        strip_prefix = "cpufeatures-0.2.17",
        build_file = Label("//bazel/cargo/remote:BUILD.cpufeatures-0.2.17.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__crypto-bigint-0.5.5",
        sha256 = "0dc92fb57ca44df6db8059111ab3af99a63d5d0f8375d9972e319a379c6bab76",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/crypto-bigint/0.5.5/download"],
        strip_prefix = "crypto-bigint-0.5.5",
        build_file = Label("//bazel/cargo/remote:BUILD.crypto-bigint-0.5.5.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__crypto-common-0.1.6",
        sha256 = "1bfb12502f3fc46cca1bb51ac28df9d618d813cdc3d2f25b9fe775a34af26bb3",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/crypto-common/0.1.6/download"],
        strip_prefix = "crypto-common-0.1.6",
        build_file = Label("//bazel/cargo/remote:BUILD.crypto-common-0.1.6.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__cssparser-0.27.2",
        sha256 = "754b69d351cdc2d8ee09ae203db831e005560fc6030da058f86ad60c92a9cb0a",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/cssparser/0.27.2/download"],
        strip_prefix = "cssparser-0.27.2",
        build_file = Label("//bazel/cargo/remote:BUILD.cssparser-0.27.2.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__cssparser-macros-0.6.1",
        sha256 = "13b588ba4ac1a99f7f2964d24b3d896ddc6bf847ee3855dbd4366f058cfcd331",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/cssparser-macros/0.6.1/download"],
        strip_prefix = "cssparser-macros-0.6.1",
        build_file = Label("//bazel/cargo/remote:BUILD.cssparser-macros-0.6.1.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__der-0.7.10",
        sha256 = "e7c1832837b905bbfb5101e07cc24c8deddf52f93225eee6ead5f4d63d53ddcb",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/der/0.7.10/download"],
        strip_prefix = "der-0.7.10",
        build_file = Label("//bazel/cargo/remote:BUILD.der-0.7.10.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__derive_more-0.99.20",
        sha256 = "6edb4b64a43d977b8e99788fe3a04d483834fba1215a7e02caa415b626497f7f",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/derive_more/0.99.20/download"],
        strip_prefix = "derive_more-0.99.20",
        build_file = Label("//bazel/cargo/remote:BUILD.derive_more-0.99.20.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__digest-0.10.7",
        sha256 = "9ed9a281f7bc9b7576e61468ba615a66a5c8cfdff42420a70aa82701a3b1e292",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/digest/0.10.7/download"],
        strip_prefix = "digest-0.10.7",
        build_file = Label("//bazel/cargo/remote:BUILD.digest-0.10.7.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__dtoa-1.0.11",
        sha256 = "4c3cf4824e2d5f025c7b531afcb2325364084a16806f6d47fbc1f5fbd9960590",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/dtoa/1.0.11/download"],
        strip_prefix = "dtoa-1.0.11",
        build_file = Label("//bazel/cargo/remote:BUILD.dtoa-1.0.11.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__dtoa-short-0.3.5",
        sha256 = "cd1511a7b6a56299bd043a9c167a6d2bfb37bf84a6dfceaba651168adfb43c87",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/dtoa-short/0.3.5/download"],
        strip_prefix = "dtoa-short-0.3.5",
        build_file = Label("//bazel/cargo/remote:BUILD.dtoa-short-0.3.5.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__ecdsa-0.16.0",
        sha256 = "cbcfcadd7eade8d8f960aa721e9731a50081694d3118c80eba744cbf68c7e5db",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/ecdsa/0.16.0/download"],
        strip_prefix = "ecdsa-0.16.0",
        build_file = Label("//bazel/cargo/remote:BUILD.ecdsa-0.16.0.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__elliptic-curve-0.13.8",
        sha256 = "b5e6043086bf7973472e0c7dff2142ea0b680d30e18d9cc40f267efbf222bd47",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/elliptic-curve/0.13.8/download"],
        strip_prefix = "elliptic-curve-0.13.8",
        build_file = Label("//bazel/cargo/remote:BUILD.elliptic-curve-0.13.8.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__encoding_rs-0.8.35",
        sha256 = "75030f3c4f45dafd7586dd6780965a8c7e8e285a5ecb86713e63a79c5b2766f3",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/encoding_rs/0.8.35/download"],
        strip_prefix = "encoding_rs-0.8.35",
        build_file = Label("//bazel/cargo/remote:BUILD.encoding_rs-0.8.35.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__ff-0.13.1",
        sha256 = "c0b50bfb653653f9ca9095b427bed08ab8d75a137839d9ad64eb11810d5b6393",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/ff/0.13.1/download"],
        strip_prefix = "ff-0.13.1",
        build_file = Label("//bazel/cargo/remote:BUILD.ff-0.13.1.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__form_urlencoded-1.2.2",
        sha256 = "cb4cb245038516f5f85277875cdaa4f7d2c9a0fa0468de06ed190163b1581fcf",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/form_urlencoded/1.2.2/download"],
        strip_prefix = "form_urlencoded-1.2.2",
        build_file = Label("//bazel/cargo/remote:BUILD.form_urlencoded-1.2.2.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__futures-core-0.3.33",
        sha256 = "2cd50c473c80f6d7c3670a752354b8e569b1a7cbfdc0419ec88e5edad85e0dc7",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/futures-core/0.3.33/download"],
        strip_prefix = "futures-core-0.3.33",
        build_file = Label("//bazel/cargo/remote:BUILD.futures-core-0.3.33.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__futures-task-0.3.33",
        sha256 = "b231ed28831efb4a61a08580c4bc233ec56bc009f4cd8f52da2c3cb97df0c109",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/futures-task/0.3.33/download"],
        strip_prefix = "futures-task-0.3.33",
        build_file = Label("//bazel/cargo/remote:BUILD.futures-task-0.3.33.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__futures-util-0.3.33",
        sha256 = "a77a90a256fce34da66415271e30f94ee91c57b04b8a2c042d9cf3220179deaa",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/futures-util/0.3.33/download"],
        strip_prefix = "futures-util-0.3.33",
        build_file = Label("//bazel/cargo/remote:BUILD.futures-util-0.3.33.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__fxhash-0.2.1",
        sha256 = "c31b6d751ae2c7f11320402d34e41349dd1016f8d5d45e48c4312bc8625af50c",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/fxhash/0.2.1/download"],
        strip_prefix = "fxhash-0.2.1",
        build_file = Label("//bazel/cargo/remote:BUILD.fxhash-0.2.1.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__generic-array-0.14.9",
        sha256 = "4bb6743198531e02858aeaea5398fcc883e71851fcbcb5a2f773e2fb6cb1edf2",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/generic-array/0.14.9/download"],
        strip_prefix = "generic-array-0.14.9",
        build_file = Label("//bazel/cargo/remote:BUILD.generic-array-0.14.9.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__getrandom-0.1.16",
        sha256 = "8fc3cb4d91f53b50155bdcfd23f6a4c39ae1969c2ae85982b135750cccaf5fce",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/getrandom/0.1.16/download"],
        strip_prefix = "getrandom-0.1.16",
        build_file = Label("//bazel/cargo/remote:BUILD.getrandom-0.1.16.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__getrandom-0.2.14",
        sha256 = "94b22e06ecb0110981051723910cbf0b5f5e09a2062dd7663334ee79a9d1286c",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/getrandom/0.2.14/download"],
        strip_prefix = "getrandom-0.2.14",
        build_file = Label("//bazel/cargo/remote:BUILD.getrandom-0.2.14.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__getrandom-0.4.3",
        sha256 = "300e883d756b2e4ec94e02791f39b04b522276138852cfc41d9fb7e904106099",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/getrandom/0.4.3/download"],
        strip_prefix = "getrandom-0.4.3",
        build_file = Label("//bazel/cargo/remote:BUILD.getrandom-0.4.3.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__group-0.13.0",
        sha256 = "f0f9ef7462f7c099f518d754361858f86d8a07af53ba9af0fe635bbccb151a63",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/group/0.13.0/download"],
        strip_prefix = "group-0.13.0",
        build_file = Label("//bazel/cargo/remote:BUILD.group-0.13.0.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__hashbrown-0.13.2",
        sha256 = "43a3c133739dddd0d2990f9a4bdf8eb4b21ef50e4851ca85ab661199821d510e",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/hashbrown/0.13.2/download"],
        strip_prefix = "hashbrown-0.13.2",
        build_file = Label("//bazel/cargo/remote:BUILD.hashbrown-0.13.2.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__hex-0.4.3",
        sha256 = "7f24254aa9a54b5c858eaee2f5bccdb46aaf0e486a595ed5fd8f86ba55232a70",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/hex/0.4.3/download"],
        strip_prefix = "hex-0.4.3",
        build_file = Label("//bazel/cargo/remote:BUILD.hex-0.4.3.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__hmac-0.12.1",
        sha256 = "6c49c37c09c17a53d937dfbb742eb3a961d65a994e6bcdcf37e7399d0cc8ab5e",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/hmac/0.12.1/download"],
        strip_prefix = "hmac-0.12.1",
        build_file = Label("//bazel/cargo/remote:BUILD.hmac-0.12.1.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__idna-0.4.0",
        sha256 = "7d20d6b07bfbc108882d88ed8e37d39636dcc260e15e30c45e6ba089610b917c",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/idna/0.4.0/download"],
        strip_prefix = "idna-0.4.0",
        build_file = Label("//bazel/cargo/remote:BUILD.idna-0.4.0.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__itoa-0.4.8",
        sha256 = "b71991ff56294aa922b450139ee08b3bfc70982c6b2c7562771375cf73542dd4",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/itoa/0.4.8/download"],
        strip_prefix = "itoa-0.4.8",
        build_file = Label("//bazel/cargo/remote:BUILD.itoa-0.4.8.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__itoa-1.0.18",
        sha256 = "8f42a60cbdf9a97f5d2305f08a87dc4e09308d1276d28c869c684d7777685682",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/itoa/1.0.18/download"],
        strip_prefix = "itoa-1.0.18",
        build_file = Label("//bazel/cargo/remote:BUILD.itoa-1.0.18.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__js-sys-0.3.103",
        sha256 = "53b44bfcdb3f8d5837a46dae1ca9660a837176eee74a28b229bc626816589102",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/js-sys/0.3.103/download"],
        strip_prefix = "js-sys-0.3.103",
        build_file = Label("//bazel/cargo/remote:BUILD.js-sys-0.3.103.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__lazy_static-1.5.0",
        sha256 = "bbd2bcb4c963f2ddae06a2efc7e9f3591312473c50c6685e1f298068316e66fe",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/lazy_static/1.5.0/download"],
        strip_prefix = "lazy_static-1.5.0",
        build_file = Label("//bazel/cargo/remote:BUILD.lazy_static-1.5.0.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__lazycell-1.3.0",
        sha256 = "830d08ce1d1d941e6b30645f1a0eb5643013d835ce3779a5fc208261dbe10f55",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/lazycell/1.3.0/download"],
        strip_prefix = "lazycell-1.3.0",
        build_file = Label("//bazel/cargo/remote:BUILD.lazycell-1.3.0.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__libc-0.2.186",
        sha256 = "68ab91017fe16c622486840e4c83c9a37afeff978bd239b5293d61ece587de66",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/libc/0.2.186/download"],
        strip_prefix = "libc-0.2.186",
        build_file = Label("//bazel/cargo/remote:BUILD.libc-0.2.186.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__log-0.4.20",
        sha256 = "b5e6163cb8c49088c2c36f57875e58ccd8c87c7427f7fbd50ea6710b2f3f2e8f",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/log/0.4.20/download"],
        strip_prefix = "log-0.4.20",
        build_file = Label("//bazel/cargo/remote:BUILD.log-0.4.20.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__lol_html-2.0.0",
        sha256 = "964b47c14635e111f7efddcd8f1f8794195f66225fef19822fa942b217a859cf",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/lol_html/2.0.0/download"],
        strip_prefix = "lol_html-2.0.0",
        build_file = Label("//bazel/cargo/remote:BUILD.lol_html-2.0.0.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__matches-0.1.10",
        sha256 = "2532096657941c2fea9c289d370a250971c689d4f143798ff67113ec042024a5",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/matches/0.1.10/download"],
        strip_prefix = "matches-0.1.10",
        build_file = Label("//bazel/cargo/remote:BUILD.matches-0.1.10.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__memchr-2.8.2",
        sha256 = "88904434abc2901f197fe8cc55f0445e7ded921dba5911dad2e2b39b48e663c4",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/memchr/2.8.2/download"],
        strip_prefix = "memchr-2.8.2",
        build_file = Label("//bazel/cargo/remote:BUILD.memchr-2.8.2.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__mime-0.3.17",
        sha256 = "6877bb514081ee2a7ff5ef9de3281f14a4dd4bceac4c09388074a6b5df8a139a",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/mime/0.3.17/download"],
        strip_prefix = "mime-0.3.17",
        build_file = Label("//bazel/cargo/remote:BUILD.mime-0.3.17.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__nodrop-0.1.14",
        sha256 = "72ef4a56884ca558e5ddb05a1d1e7e1bfd9a68d9ed024c21704cc98872dae1bb",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/nodrop/0.1.14/download"],
        strip_prefix = "nodrop-0.1.14",
        build_file = Label("//bazel/cargo/remote:BUILD.nodrop-0.1.14.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__once_cell-1.19.0",
        sha256 = "3fdb12b2476b595f9358c5161aa467c2438859caa136dec86c26fdd2efe17b92",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/once_cell/1.19.0/download"],
        strip_prefix = "once_cell-1.19.0",
        build_file = Label("//bazel/cargo/remote:BUILD.once_cell-1.19.0.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__p256-0.13.0",
        sha256 = "7270da3e5caa82afd3deb054cc237905853813aea3859544bc082c3fe55b8d47",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/p256/0.13.0/download"],
        strip_prefix = "p256-0.13.0",
        build_file = Label("//bazel/cargo/remote:BUILD.p256-0.13.0.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__percent-encoding-2.3.2",
        sha256 = "9b4f627cb1b25917193a259e49bdad08f671f8d9708acfd5fe0a8c1455d87220",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/percent-encoding/2.3.2/download"],
        strip_prefix = "percent-encoding-2.3.2",
        build_file = Label("//bazel/cargo/remote:BUILD.percent-encoding-2.3.2.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__phf-0.8.0",
        sha256 = "3dfb61232e34fcb633f43d12c58f83c1df82962dcdfa565a4e866ffc17dafe12",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/phf/0.8.0/download"],
        strip_prefix = "phf-0.8.0",
        build_file = Label("//bazel/cargo/remote:BUILD.phf-0.8.0.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__phf_codegen-0.8.0",
        sha256 = "cbffee61585b0411840d3ece935cce9cb6321f01c45477d30066498cd5e1a815",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/phf_codegen/0.8.0/download"],
        strip_prefix = "phf_codegen-0.8.0",
        build_file = Label("//bazel/cargo/remote:BUILD.phf_codegen-0.8.0.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__phf_generator-0.8.0",
        sha256 = "17367f0cc86f2d25802b2c26ee58a7b23faeccf78a396094c13dced0d0182526",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/phf_generator/0.8.0/download"],
        strip_prefix = "phf_generator-0.8.0",
        build_file = Label("//bazel/cargo/remote:BUILD.phf_generator-0.8.0.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__phf_macros-0.8.0",
        sha256 = "7f6fde18ff429ffc8fe78e2bf7f8b7a5a5a6e2a8b58bc5a9ac69198bbda9189c",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/phf_macros/0.8.0/download"],
        strip_prefix = "phf_macros-0.8.0",
        build_file = Label("//bazel/cargo/remote:BUILD.phf_macros-0.8.0.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__phf_shared-0.8.0",
        sha256 = "c00cf8b9eafe68dde5e9eaa2cef8ee84a9336a47d566ec55ca16589633b65af7",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/phf_shared/0.8.0/download"],
        strip_prefix = "phf_shared-0.8.0",
        build_file = Label("//bazel/cargo/remote:BUILD.phf_shared-0.8.0.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__pin-project-lite-0.2.17",
        sha256 = "a89322df9ebe1c1578d689c92318e070967d1042b512afbe49518723f4e6d5cd",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/pin-project-lite/0.2.17/download"],
        strip_prefix = "pin-project-lite-0.2.17",
        build_file = Label("//bazel/cargo/remote:BUILD.pin-project-lite-0.2.17.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__ppv-lite86-0.2.21",
        sha256 = "85eae3c4ed2f50dcfe72643da4befc30deadb458a9b590d720cde2f2b1e97da9",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/ppv-lite86/0.2.21/download"],
        strip_prefix = "ppv-lite86-0.2.21",
        build_file = Label("//bazel/cargo/remote:BUILD.ppv-lite86-0.2.21.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__precomputed-hash-0.1.1",
        sha256 = "925383efa346730478fb4838dbe9137d2a47675ad789c546d150a6e1dd4ab31c",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/precomputed-hash/0.1.1/download"],
        strip_prefix = "precomputed-hash-0.1.1",
        build_file = Label("//bazel/cargo/remote:BUILD.precomputed-hash-0.1.1.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__primeorder-0.13.6",
        sha256 = "353e1ca18966c16d9deb1c69278edbc5f194139612772bd9537af60ac231e1e6",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/primeorder/0.13.6/download"],
        strip_prefix = "primeorder-0.13.6",
        build_file = Label("//bazel/cargo/remote:BUILD.primeorder-0.13.6.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__proc-macro-hack-0.5.20-deprecated",
        sha256 = "dc375e1527247fe1a97d8b7156678dfe7c1af2fc075c9a4db3690ecd2a148068",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/proc-macro-hack/0.5.20+deprecated/download"],
        strip_prefix = "proc-macro-hack-0.5.20+deprecated",
        build_file = Label("//bazel/cargo/remote:BUILD.proc-macro-hack-0.5.20+deprecated.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__proc-macro2-1.0.106",
        sha256 = "8fd00f0bb2e90d81d1044c2b32617f68fcb9fa3bb7640c23e9c748e53fb30934",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/proc-macro2/1.0.106/download"],
        strip_prefix = "proc-macro2-1.0.106",
        build_file = Label("//bazel/cargo/remote:BUILD.proc-macro2-1.0.106.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__proxy-wasm-0.2.1",
        sha256 = "823b744520cd4a54ba7ebacbffe4562e839d6dcd8f89209f96a1ace4f5229cd4",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/proxy-wasm/0.2.1/download"],
        strip_prefix = "proxy-wasm-0.2.1",
        build_file = Label("//bazel/cargo/remote:BUILD.proxy-wasm-0.2.1.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__quote-1.0.46",
        sha256 = "dfbc457d0c7a0759a614551b11a6409e5951f6c7537be1f1b7682b9ae9230368",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/quote/1.0.46/download"],
        strip_prefix = "quote-1.0.46",
        build_file = Label("//bazel/cargo/remote:BUILD.quote-1.0.46.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__r-efi-6.0.0",
        sha256 = "f8dcc9c7d52a811697d2151c701e0d08956f92b0e24136cf4cf27b57a6a0d9bf",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/r-efi/6.0.0/download"],
        strip_prefix = "r-efi-6.0.0",
        build_file = Label("//bazel/cargo/remote:BUILD.r-efi-6.0.0.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__rand-0.7.3",
        sha256 = "6a6b1679d49b24bbfe0c803429aa1874472f50d9b363131f0e89fc356b544d03",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/rand/0.7.3/download"],
        strip_prefix = "rand-0.7.3",
        build_file = Label("//bazel/cargo/remote:BUILD.rand-0.7.3.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__rand_chacha-0.2.2",
        sha256 = "f4c8ed856279c9737206bf725bf36935d8666ead7aa69b52be55af369d193402",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/rand_chacha/0.2.2/download"],
        strip_prefix = "rand_chacha-0.2.2",
        build_file = Label("//bazel/cargo/remote:BUILD.rand_chacha-0.2.2.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__rand_core-0.5.1",
        sha256 = "90bde5296fc891b0cef12a6d03ddccc162ce7b2aff54160af9338f8d40df6d19",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/rand_core/0.5.1/download"],
        strip_prefix = "rand_core-0.5.1",
        build_file = Label("//bazel/cargo/remote:BUILD.rand_core-0.5.1.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__rand_core-0.6.4",
        sha256 = "ec0be4795e2f6a28069bec0b5ff3e2ac9bafc99e6a9a7dc3547996c5c816922c",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/rand_core/0.6.4/download"],
        strip_prefix = "rand_core-0.6.4",
        build_file = Label("//bazel/cargo/remote:BUILD.rand_core-0.6.4.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__rand_hc-0.2.0",
        sha256 = "ca3129af7b92a17112d59ad498c6f81eaf463253766b90396d39ea7a39d6613c",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/rand_hc/0.2.0/download"],
        strip_prefix = "rand_hc-0.2.0",
        build_file = Label("//bazel/cargo/remote:BUILD.rand_hc-0.2.0.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__rand_pcg-0.2.1",
        sha256 = "16abd0c1b639e9eb4d7c50c0b8100b0d0f849be2349829c740fe8e6eb4816429",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/rand_pcg/0.2.1/download"],
        strip_prefix = "rand_pcg-0.2.1",
        build_file = Label("//bazel/cargo/remote:BUILD.rand_pcg-0.2.1.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__regex-1.9.6",
        sha256 = "ebee201405406dbf528b8b672104ae6d6d63e6d118cb10e4d51abbc7b58044ff",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/regex/1.9.6/download"],
        strip_prefix = "regex-1.9.6",
        build_file = Label("//bazel/cargo/remote:BUILD.regex-1.9.6.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__regex-automata-0.3.9",
        sha256 = "59b23e92ee4318893fa3fe3e6fb365258efbfe6ac6ab30f090cdcbb7aa37efa9",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/regex-automata/0.3.9/download"],
        strip_prefix = "regex-automata-0.3.9",
        build_file = Label("//bazel/cargo/remote:BUILD.regex-automata-0.3.9.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__regex-syntax-0.7.5",
        sha256 = "dbb5fb1acd8a1a18b3dd5be62d25485eb770e05afb408a9627d14d451bae12da",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/regex-syntax/0.7.5/download"],
        strip_prefix = "regex-syntax-0.7.5",
        build_file = Label("//bazel/cargo/remote:BUILD.regex-syntax-0.7.5.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__rfc6979-0.4.0",
        sha256 = "f8dd2a808d456c4a54e300a23e9f5a67e122c3024119acbfd73e3bf664491cb2",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/rfc6979/0.4.0/download"],
        strip_prefix = "rfc6979-0.4.0",
        build_file = Label("//bazel/cargo/remote:BUILD.rfc6979-0.4.0.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__rustc_version-0.4.1",
        sha256 = "cfcb3a22ef46e85b45de6ee7e79d063319ebb6594faafcf1c225ea92ab6e9b92",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/rustc_version/0.4.1/download"],
        strip_prefix = "rustc_version-0.4.1",
        build_file = Label("//bazel/cargo/remote:BUILD.rustc_version-0.4.1.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__rustversion-1.0.23",
        sha256 = "cf54715a573b99ac80df0bc206da022bcd442c974952c7b9720069370852e21f",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/rustversion/1.0.23/download"],
        strip_prefix = "rustversion-1.0.23",
        build_file = Label("//bazel/cargo/remote:BUILD.rustversion-1.0.23.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__ryu-1.0.23",
        sha256 = "9774ba4a74de5f7b1c1451ed6cd5285a32eddb5cccb8cc655a4e50009e06477f",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/ryu/1.0.23/download"],
        strip_prefix = "ryu-1.0.23",
        build_file = Label("//bazel/cargo/remote:BUILD.ryu-1.0.23.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__sec1-0.7.3",
        sha256 = "d3e97a565f76233a6003f9f5c54be1d9c5bdfa3eccfb189469f11ec4901c47dc",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/sec1/0.7.3/download"],
        strip_prefix = "sec1-0.7.3",
        build_file = Label("//bazel/cargo/remote:BUILD.sec1-0.7.3.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__selectors-0.22.0",
        sha256 = "df320f1889ac4ba6bc0cdc9c9af7af4bd64bb927bccdf32d81140dc1f9be12fe",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/selectors/0.22.0/download"],
        strip_prefix = "selectors-0.22.0",
        build_file = Label("//bazel/cargo/remote:BUILD.selectors-0.22.0.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__semver-1.0.28",
        sha256 = "8a7852d02fc848982e0c167ef163aaff9cd91dc640ba85e263cb1ce46fae51cd",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/semver/1.0.28/download"],
        strip_prefix = "semver-1.0.28",
        build_file = Label("//bazel/cargo/remote:BUILD.semver-1.0.28.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__serde-1.0.197",
        sha256 = "3fb1c873e1b9b056a4dc4c0c198b24c3ffa059243875552b2bd0933b1aee4ce2",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/serde/1.0.197/download"],
        strip_prefix = "serde-1.0.197",
        build_file = Label("//bazel/cargo/remote:BUILD.serde-1.0.197.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__serde_derive-1.0.197",
        sha256 = "7eb0b34b42edc17f6b7cac84a52a1c5f0e1bb2227e997ca9011ea3dd34e8610b",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/serde_derive/1.0.197/download"],
        strip_prefix = "serde_derive-1.0.197",
        build_file = Label("//bazel/cargo/remote:BUILD.serde_derive-1.0.197.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__serde_json-1.0.114",
        sha256 = "c5f09b1bd632ef549eaa9f60a1f8de742bdbc698e6cee2095fc84dde5f549ae0",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/serde_json/1.0.114/download"],
        strip_prefix = "serde_json-1.0.114",
        build_file = Label("//bazel/cargo/remote:BUILD.serde_json-1.0.114.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__servo_arc-0.1.1",
        sha256 = "d98238b800e0d1576d8b6e3de32827c2d74bee68bb97748dcf5071fb53965432",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/servo_arc/0.1.1/download"],
        strip_prefix = "servo_arc-0.1.1",
        build_file = Label("//bazel/cargo/remote:BUILD.servo_arc-0.1.1.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__sha2-0.10.8",
        sha256 = "793db75ad2bcafc3ffa7c68b215fee268f537982cd901d132f89c6343f3a3dc8",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/sha2/0.10.8/download"],
        strip_prefix = "sha2-0.10.8",
        build_file = Label("//bazel/cargo/remote:BUILD.sha2-0.10.8.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__signature-2.0.0",
        sha256 = "8fe458c98333f9c8152221191a77e2a44e8325d0193484af2e9421a53019e57d",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/signature/2.0.0/download"],
        strip_prefix = "signature-2.0.0",
        build_file = Label("//bazel/cargo/remote:BUILD.signature-2.0.0.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__siphasher-0.3.11",
        sha256 = "38b58827f4464d87d377d175e90bf58eb00fd8716ff0a62f80356b5e61555d0d",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/siphasher/0.3.11/download"],
        strip_prefix = "siphasher-0.3.11",
        build_file = Label("//bazel/cargo/remote:BUILD.siphasher-0.3.11.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__slab-0.4.12",
        sha256 = "0c790de23124f9ab44544d7ac05d60440adc586479ce501c1d6d7da3cd8c9cf5",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/slab/0.4.12/download"],
        strip_prefix = "slab-0.4.12",
        build_file = Label("//bazel/cargo/remote:BUILD.slab-0.4.12.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__smallvec-1.15.2",
        sha256 = "8ed6a63f02c8539c91a8685a86f4099661ba3da017932f6ebbea6de3f0fa7c90",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/smallvec/1.15.2/download"],
        strip_prefix = "smallvec-1.15.2",
        build_file = Label("//bazel/cargo/remote:BUILD.smallvec-1.15.2.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__stable_deref_trait-1.2.1",
        sha256 = "6ce2be8dc25455e1f91df71bfa12ad37d7af1092ae736f3a6cd0e37bc7810596",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/stable_deref_trait/1.2.1/download"],
        strip_prefix = "stable_deref_trait-1.2.1",
        build_file = Label("//bazel/cargo/remote:BUILD.stable_deref_trait-1.2.1.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__subtle-2.6.1",
        sha256 = "13c2bddecc57b384dee18652358fb23172facb8a2c51ccc10d74c157bdea3292",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/subtle/2.6.1/download"],
        strip_prefix = "subtle-2.6.1",
        build_file = Label("//bazel/cargo/remote:BUILD.subtle-2.6.1.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__syn-1.0.109",
        sha256 = "72b64191b275b66ffe2469e8af2c1cfe3bafa67b529ead792a6d0160888b4237",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/syn/1.0.109/download"],
        strip_prefix = "syn-1.0.109",
        build_file = Label("//bazel/cargo/remote:BUILD.syn-1.0.109.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__syn-2.0.118",
        sha256 = "1b9ae57f904213ebb649ce6895b8a66c66f0203b9319718f69a5612a065b1422",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/syn/2.0.118/download"],
        strip_prefix = "syn-2.0.118",
        build_file = Label("//bazel/cargo/remote:BUILD.syn-2.0.118.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__thin-slice-0.1.1",
        sha256 = "8eaa81235c7058867fa8c0e7314f33dcce9c215f535d1913822a2b3f5e289f3c",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/thin-slice/0.1.1/download"],
        strip_prefix = "thin-slice-0.1.1",
        build_file = Label("//bazel/cargo/remote:BUILD.thin-slice-0.1.1.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__thiserror-1.0.69",
        sha256 = "b6aaf5339b578ea85b50e080feb250a3e8ae8cfcdff9a461c9ec2904bc923f52",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/thiserror/1.0.69/download"],
        strip_prefix = "thiserror-1.0.69",
        build_file = Label("//bazel/cargo/remote:BUILD.thiserror-1.0.69.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__thiserror-impl-1.0.69",
        sha256 = "4fee6c4efc90059e10f81e6d42c60a18f76588c3d74cb83a0b242a2b6c7504c1",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/thiserror-impl/1.0.69/download"],
        strip_prefix = "thiserror-impl-1.0.69",
        build_file = Label("//bazel/cargo/remote:BUILD.thiserror-impl-1.0.69.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__tinyvec-1.11.0",
        sha256 = "3e61e67053d25a4e82c844e8424039d9745781b3fc4f32b8d55ed50f5f667ef3",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/tinyvec/1.11.0/download"],
        strip_prefix = "tinyvec-1.11.0",
        build_file = Label("//bazel/cargo/remote:BUILD.tinyvec-1.11.0.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__tinyvec_macros-0.1.1",
        sha256 = "1f3ccbac311fea05f86f61904b462b55fb3df8837a366dfc601a0161d0532f20",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/tinyvec_macros/0.1.1/download"],
        strip_prefix = "tinyvec_macros-0.1.1",
        build_file = Label("//bazel/cargo/remote:BUILD.tinyvec_macros-0.1.1.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__typenum-1.20.1",
        sha256 = "b6f5e870be6c3b371b77fe0ee0bafb859fa4964b4404c27de1d380043c4dda20",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/typenum/1.20.1/download"],
        strip_prefix = "typenum-1.20.1",
        build_file = Label("//bazel/cargo/remote:BUILD.typenum-1.20.1.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__unicode-bidi-0.3.18",
        sha256 = "5c1cb5db39152898a79168971543b1cb5020dff7fe43c8dc468b0885f5e29df5",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/unicode-bidi/0.3.18/download"],
        strip_prefix = "unicode-bidi-0.3.18",
        build_file = Label("//bazel/cargo/remote:BUILD.unicode-bidi-0.3.18.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__unicode-ident-1.0.24",
        sha256 = "e6e4313cd5fcd3dad5cafa179702e2b244f760991f45397d14d4ebf38247da75",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/unicode-ident/1.0.24/download"],
        strip_prefix = "unicode-ident-1.0.24",
        build_file = Label("//bazel/cargo/remote:BUILD.unicode-ident-1.0.24.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__unicode-normalization-0.1.25",
        sha256 = "5fd4f6878c9cb28d874b009da9e8d183b5abc80117c40bbd187a1fde336be6e8",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/unicode-normalization/0.1.25/download"],
        strip_prefix = "unicode-normalization-0.1.25",
        build_file = Label("//bazel/cargo/remote:BUILD.unicode-normalization-0.1.25.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__url-2.4.0",
        sha256 = "50bff7831e19200a85b17131d085c25d7811bc4e186efdaf54bbd132994a88cb",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/url/2.4.0/download"],
        strip_prefix = "url-2.4.0",
        build_file = Label("//bazel/cargo/remote:BUILD.url-2.4.0.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__uuid-1.24.0",
        sha256 = "bf3923a6f5c4c6382e0b653c4117f48d631ea17f38ed86e2a828e6f7412f5239",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/uuid/1.24.0/download"],
        strip_prefix = "uuid-1.24.0",
        build_file = Label("//bazel/cargo/remote:BUILD.uuid-1.24.0.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__version_check-0.9.5",
        sha256 = "0b928f33d975fc6ad9f86c8f283853ad26bdd5b10b7f1542aa2fa15e2289105a",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/version_check/0.9.5/download"],
        strip_prefix = "version_check-0.9.5",
        build_file = Label("//bazel/cargo/remote:BUILD.version_check-0.9.5.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__wasi-0.11.1-wasi-snapshot-preview1",
        sha256 = "ccf3ec651a847eb01de73ccad15eb7d99f80485de043efb2f370cd654f4ea44b",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/wasi/0.11.1+wasi-snapshot-preview1/download"],
        strip_prefix = "wasi-0.11.1+wasi-snapshot-preview1",
        build_file = Label("//bazel/cargo/remote:BUILD.wasi-0.11.1+wasi-snapshot-preview1.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__wasi-0.9.0-wasi-snapshot-preview1",
        sha256 = "cccddf32554fecc6acb585f82a32a72e28b48f8c4c1883ddfeeeaa96f7d8e519",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/wasi/0.9.0+wasi-snapshot-preview1/download"],
        strip_prefix = "wasi-0.9.0+wasi-snapshot-preview1",
        build_file = Label("//bazel/cargo/remote:BUILD.wasi-0.9.0+wasi-snapshot-preview1.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__wasm-bindgen-0.2.126",
        sha256 = "4b067c0c11094aef6b7a801c1e34a26affafdf3d051dba08456b868789aaf9a4",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/wasm-bindgen/0.2.126/download"],
        strip_prefix = "wasm-bindgen-0.2.126",
        build_file = Label("//bazel/cargo/remote:BUILD.wasm-bindgen-0.2.126.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__wasm-bindgen-macro-0.2.126",
        sha256 = "167ce5e579f6bcf889c4f7175a8a5a585de84e8ff93976ce393efa5f2837aab1",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/wasm-bindgen-macro/0.2.126/download"],
        strip_prefix = "wasm-bindgen-macro-0.2.126",
        build_file = Label("//bazel/cargo/remote:BUILD.wasm-bindgen-macro-0.2.126.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__wasm-bindgen-macro-support-0.2.126",
        sha256 = "f3997c7839262f4ef12cf90b818d6340c18e80f263f1a94bf157d0ec4420380e",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/wasm-bindgen-macro-support/0.2.126/download"],
        strip_prefix = "wasm-bindgen-macro-support-0.2.126",
        build_file = Label("//bazel/cargo/remote:BUILD.wasm-bindgen-macro-support-0.2.126.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__wasm-bindgen-shared-0.2.126",
        sha256 = "dc1b4cb0cc549fcf58d7dfc081778139b3d283a081644e833e84682ad71cea24",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/wasm-bindgen-shared/0.2.126/download"],
        strip_prefix = "wasm-bindgen-shared-0.2.126",
        build_file = Label("//bazel/cargo/remote:BUILD.wasm-bindgen-shared-0.2.126.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__zerocopy-0.8.53",
        sha256 = "75726053136156d419e285b9b7eddaaea9e3fea6ce32eed44a89901f0bd98de1",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/zerocopy/0.8.53/download"],
        strip_prefix = "zerocopy-0.8.53",
        build_file = Label("//bazel/cargo/remote:BUILD.zerocopy-0.8.53.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__zerocopy-derive-0.8.53",
        sha256 = "4714fd92cf900833d49538023a9b3915155210801d1c1169eba513b2addefd71",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/zerocopy-derive/0.8.53/download"],
        strip_prefix = "zerocopy-derive-0.8.53",
        build_file = Label("//bazel/cargo/remote:BUILD.zerocopy-derive-0.8.53.bazel"),
    )

    maybe(
        http_archive,
        name = "cu__zeroize-1.8.1",
        sha256 = "ced3678a2879b30306d323f4542626697a464a97c0a07c9aebf7ebca65cd4dde",
        type = "tar.gz",
        urls = ["https://static.crates.io/crates/zeroize/1.8.1/download"],
        strip_prefix = "zeroize-1.8.1",
        build_file = Label("//bazel/cargo/remote:BUILD.zeroize-1.8.1.bazel"),
    )

    return [
        struct(repo = "cu__ecdsa-0.16.0", is_dev_dep = False),
        struct(repo = "cu__getrandom-0.2.14", is_dev_dep = False),
        struct(repo = "cu__hex-0.4.3", is_dev_dep = False),
        struct(repo = "cu__hmac-0.12.1", is_dev_dep = False),
        struct(repo = "cu__log-0.4.20", is_dev_dep = False),
        struct(repo = "cu__lol_html-2.0.0", is_dev_dep = False),
        struct(repo = "cu__once_cell-1.19.0", is_dev_dep = False),
        struct(repo = "cu__p256-0.13.0", is_dev_dep = False),
        struct(repo = "cu__proxy-wasm-0.2.1", is_dev_dep = False),
        struct(repo = "cu__rand_core-0.6.4", is_dev_dep = False),
        struct(repo = "cu__regex-1.9.6", is_dev_dep = False),
        struct(repo = "cu__serde-1.0.197", is_dev_dep = False),
        struct(repo = "cu__serde_json-1.0.114", is_dev_dep = False),
        struct(repo = "cu__sha2-0.10.8", is_dev_dep = False),
        struct(repo = "cu__url-2.4.0", is_dev_dep = False),
        struct(repo = "cu__uuid-1.24.0", is_dev_dep = False),
        struct(repo = "cu__zeroize-1.8.1", is_dev_dep = False),
    ]
