#!/usr/bin/env python3
# Copyright 2026 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Generates callouts/CATALOG.md from frontmatter in example READMEs.

Any README.md under callouts/ that starts with a YAML-ish frontmatter
block containing a `use_case:` key is treated as an indexed example.
READMEs with no frontmatter (index pages, service docs, deploy guides)
are skipped automatically -- there's no separate include-list to keep
in sync.

Usage:
    python3 callouts/scripts/generate_catalog.py [--check]

--check exits non-zero if CATALOG.md would change (for CI), instead of
writing the file.
"""

import argparse
import pathlib
import re
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
CALLOUTS_DIR = REPO_ROOT / "callouts"
CATALOG_PATH = CALLOUTS_DIR / "CATALOG.md"

# Fixed display order + title for each use_case id.
USE_CASE_ORDER = [
    ("header-manipulation", "Header manipulation"),
    ("body-manipulation", "Body manipulation"),
    ("routing-traffic", "Routing & traffic"),
    ("auth", "Authentication & authorization"),
    ("cookie-management", "Cookie management"),
    ("observability", "Observability"),
    ("ai-llm-gateway", "AI / LLM gateway"),
    ("network-l4", "Network-layer (L4)"),
]

FRONTMATTER_RE = re.compile(r"^<!--\ncallout-catalog:\n(.*?\n)-->\n", re.DOTALL)


def parse_frontmatter(text):
    """Tiny hand-rolled frontmatter parser -- no PyYAML dependency.

    Frontmatter lives inside an HTML comment (`<!-- callout-catalog: ... -->`)
    at the very top of the file, so it parses as metadata but never renders
    as visible clutter when GitHub shows the README normally.

    Supports flat, two-space-indented `key: value` pairs and one-level
    `key: [a, b, c]` lists. Returns None if the file has no leading
    frontmatter block.
    """
    m = FRONTMATTER_RE.match(text)
    if not m:
        return None
    fields = {}
    for line in m.group(1).splitlines():
        line = line.strip()
        if not line or line.startswith("#") or ":" not in line:
            continue
        key, _, value = line.partition(":")
        key = key.strip()
        value = value.strip()
        if value.startswith("[") and value.endswith("]"):
            items = [v.strip().strip('"').strip("'") for v in value[1:-1].split(",") if v.strip()]
            fields[key] = items
        else:
            fields[key] = value.strip('"').strip("'")
    return fields


def collect_examples():
    examples = []
    for readme in sorted(CALLOUTS_DIR.rglob("README.md")):
        text = readme.read_text(encoding="utf-8")
        fm = parse_frontmatter(text)
        if not fm or "use_case" not in fm:
            continue
        rel_dir = readme.parent.relative_to(CALLOUTS_DIR)
        fm["_link"] = str(rel_dir) + "/"
        fm["_name"] = readme.parent.name
        examples.append(fm)
    return examples


def render(examples):
    by_use_case = {uc: [] for uc, _ in USE_CASE_ORDER}
    for ex in examples:
        by_use_case.setdefault(ex["use_case"], []).append(ex)

    lines = [
        "<!-- Generated by callouts/scripts/generate_catalog.py -- do not edit by hand. -->",
        "# Callout catalog",
        "",
        "Every example in this directory, indexed by use case. Regenerate after adding or",
        "editing an example's frontmatter:",
        "",
        "```bash",
        "python3 callouts/scripts/generate_catalog.py",
        "```",
        "",
        "| Use case | Examples |",
        "|---|---|",
    ]
    for uc_id, uc_title in USE_CASE_ORDER:
        count = len(by_use_case.get(uc_id, []))
        lines.append(f"| [{uc_title}](#{uc_id}) | {count} |")
    lines.append("")

    for uc_id, uc_title in USE_CASE_ORDER:
        rows = by_use_case.get(uc_id, [])
        lines.append(f'<a id="{uc_id}"></a>')
        lines.append(f"## {uc_title}")
        lines.append("")
        if not rows:
            lines.append("_No examples yet._")
            lines.append("")
            continue
        lines.append("| Example | Language | Protocol | Summary |")
        lines.append("|---|---|---|---|")
        for ex in sorted(rows, key=lambda e: (e.get("language", ""), e["_name"])):
            name = ex["_name"]
            link = ex["_link"]
            language = ex.get("language", "?").capitalize()
            protocol = ex.get("protocol", "?")
            summary = ex.get("summary", "")
            lines.append(f"| [{name}]({link}) | {language} | `{protocol}` | {summary} |")
        lines.append("")

    # Any use_case ids found in the wild that aren't in USE_CASE_ORDER still get listed,
    # so a new category shows up instead of silently vanishing.
    unknown = sorted(set(by_use_case) - {uc for uc, _ in USE_CASE_ORDER})
    for uc_id in unknown:
        rows = by_use_case[uc_id]
        lines.append(f'<a id="{uc_id}"></a>')
        lines.append(f"## {uc_id} _(uncategorized -- add this id to USE_CASE_ORDER)_")
        lines.append("")
        for ex in rows:
            lines.append(f"- [{ex['_name']}]({ex['_link']}) ({ex.get('language','?')})")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                         help="exit 1 if CATALOG.md would change, without writing it")
    args = parser.parse_args()

    examples = collect_examples()
    rendered = render(examples)

    if args.check:
        current = CATALOG_PATH.read_text(encoding="utf-8") if CATALOG_PATH.exists() else ""
        if current != rendered:
            print("callouts/CATALOG.md is stale. Run: python3 callouts/scripts/generate_catalog.py",
                  file=sys.stderr)
            return 1
        print(f"callouts/CATALOG.md is up to date ({len(examples)} examples).")
        return 0

    CATALOG_PATH.write_text(rendered, encoding="utf-8")
    print(f"Wrote {CATALOG_PATH} ({len(examples)} examples).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
