package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2

cc_binary(
    name = "basic_cpp",
    srcs = ["basic.cc"],
    deps = [
        "//:callout_service_cpp_lib",
    ],
)

# cc_test(
#     name = "tests",
#     plugins = [
#         ":callout_service_cpp",
#     ],
#     tests = ":tests.textpb",
# )
