package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2

filegroup(
    name = "ssl_creds",
    srcs = [
        "privatekey.pem",
        "publickey.pem",
        "chain.pem",
    ],
)