# This workflow will install Java dependencies, run tests and lint with a single version of Java

name: Callouts test Java SDK

on:
  push:
    branches: [ "main" ]
    paths:
      - callouts/java/**
  pull_request:
    branches: [ "main" ]
    paths:
      - callouts/java/**

# Default permissions are read-only.
permissions: read-all

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      # Workflow can publish documentation
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Install dependencies (Maven)
        working-directory: callouts/java/service-callout/
        run: mvn install --no-transfer-progress

      - name: Run Tests (Maven)
        working-directory: callouts/java/service-callout/
        run: mvn test --no-transfer-progress

      - name: Generate Javadocs
        working-directory: callouts/java/service-callout/
        run: mvn javadoc:javadoc

      - name: Copy Javadocs to Build Directory
        run: |
          mkdir -p docs/java/_build
          cp -r callouts/java/service-callout/target/reports/apidocs/* docs/java/_build/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/java/_build
          destination_dir: java/_build
          keep_files: false
          force_orphan: false
