name: Plugins publish wasm tester

# Manually invoked. Permissions default to those with repo `write` access.
# https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow
on: workflow_dispatch

# Default permissions are read only.
permissions: read-all

# Variables. The workflow also depends on secrets.GAR_PLUGINS_TOKEN.
env:
  REGISTRY: us-docker.pkg.dev
  PROJECT: service-extensions-samples
  REPOSITORY: ${{ github.repository_owner == 'GoogleCloudPlatform' && 'plugins-source' || 'plugins-testing-source' }}
  IMAGE: wasm-tester
  DOCKERFILE: test/package/Dockerfile

jobs:
  build-and-push-image:
    name: Publish plugin tester
    runs-on: ubuntu-latest

    # Permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read

    # TODO add linux/arm64 (aarch64) build via matrix and cross-compile
    # https://github.com/GoogleCloudPlatform/service-extensions-samples/blob/main/.github/workflows/test.yml#L38
    # https://github.com/proxy-wasm/proxy-wasm-cpp-host/blob/04dfb94747e6462b65f7ed694e2d9c78ab207e11/.bazelrc#L72
    # https://github.com/docker/build-push-action/issues/529#issuecomment-1001080311

    steps:
      # Get latest repo.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Authenticate to GAR.
      - name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: _json_key
          password: ${{ secrets.GAR_PLUGINS_TOKEN }}

      # Get metadata: https://github.com/docker/metadata-action#about
      # The `images` value provides the base name for tags and labels.
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.PROJECT }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}
          tags: |
            type=ref,event=branch
            type=sha,prefix=public-image-,format=short
          labels: |
            org.opencontainers.image.title=Wasm Tester
            org.opencontainers.image.description=Wasm plugin test runner

      # Push Docker image: https://github.com/docker/build-push-action#about
      # Uses the `tags` and `labels` from the `meta` step.
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: ./plugins
          file: ./plugins/${{ env.DOCKERFILE }}
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

