FROM alpine:3.19

USER root

# Install ghz (gRPC benchmarking tool) and dependencies
RUN apk add --no-cache \
    curl \
    jq \
    bash \
    docker-cli \
    git \
    procps \
    htop \
    bc \
    && curl -sSL https://github.com/bojand/ghz/releases/download/v0.120.0/ghz-linux-x86_64.tar.gz \
    | tar -xz -C /usr/local/bin ghz

WORKDIR /workspace

COPY run-test.sh ./
COPY lib/ ./lib/
COPY config/test-config.json ./config/
RUN chmod +x run-test.sh && chmod +x lib/*.sh

COPY proto/ ./proto/

RUN mkdir -p results

CMD ["./run-test.sh", "-h"]
